accessToken: AAAAAAAAAAAAAAAAAAAAAA
appID: BBBBBBBBBBBBBBBBBBBBBBBBBB
appSecret: CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCc
serverToken: ZZZZZZZZZZZZZZZZZZZZZZZZ
tempID: XXXXXXXXXXXXXXXXXXXXXXXx
tokenExpires: 2021-07-02 21:07:17.643057
